# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 07:49
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosting', '0051_whereabouts_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlottablePlace',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('hosting.place',),
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
