# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0019_auto_20161001_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='sporadic_presence',
            field=models.BooleanField(default=False, help_text='If you are not often at this address and need an advance notification.', verbose_name='irregularly present'),
        ),
        migrations.AlterField(
            model_name='place',
            name='in_book',
            field=models.BooleanField(default=True, help_text='If you want this place to be in the printed book. Must be available.', verbose_name='print in book'),
        ),
    ]
