# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 23:23
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hosting", "0024_auto_20161019_2256"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMember",
            fields=[],
            options={
                "proxy": True,
                "ordering": ["first_name", "last_name", "id"],
            },
            bases=("hosting.profile",),
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
