# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:24
from __future__ import unicode_literals

from django.db import migrations

from django_countries import data

COUNTRIES = sorted(dict(data.COUNTRIES).keys())


def create_country_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for country in COUNTRIES:
        Group.objects.get_or_create(name=country)


def delete_country_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=COUNTRIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('hosting', '0025_auto_20161019_2323'),
    ]

    operations = [
        migrations.RunPython(create_country_groups, reverse_code=delete_country_groups)
    ]
