# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0026_create_country_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='names_inversed',
            field=models.BooleanField(default=False, verbose_name='names in inverse order'),
        ),
    ]
