# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0029_tracking_fields_using_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='place',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='place',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='website',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='website',
            name='deleted',
        ),
    ]
