# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models, transaction


def populate_profile_email(apps, schema_editor):
    profiles = apps.get_model('hosting', 'Profile')._default_manager.filter(
        user__isnull=False).exclude(
        user__email__startswith='INVALID_')
    with transaction.atomic():
        for profile in profiles:
            profile.email = profile.user.email
            profile.save()


def unpopulate_profile_email(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0030_remove_boolean_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='This email address will be used for the book. Leave blank if you don’t want this email to be public.\nThe system will never send emails to this address.', max_length=254, verbose_name='profile email'),
        ),

        migrations.RunPython(populate_profile_email, unpopulate_profile_email)
    ]
