# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:39
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('hosting', '0033_condition_latex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted on'),
        ),
        migrations.AlterField(
            model_name='place',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted on'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted on'),
        ),
        migrations.AlterField(
            model_name='website',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted on'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text="This email address will be used for the book. Leave blank if you don't want this email to be public.\nThe system will never send emails to this address, neither publish it on the site without your permission.", max_length=254, verbose_name='public email'),
        ),
    ]
