# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0034_auto_20170218_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='blocked_from',
            field=models.DateField(blank=True, null=True, verbose_name='unavailable from'),
        ),
        migrations.AddField(
            model_name='place',
            name='blocked_until',
            field=models.DateField(blank=True, null=True, verbose_name='unavailable until'),
        ),
    ]
