# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 15:10
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0033_condition_latex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'permissions': (('can_supervise', 'Can modify users from specific country'),),
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
