# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0038_add_approver_proxy_model'),
        ('hosting', '0035_place_blocking_dates'),
    ]

    operations = [
    ]
