# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0040_add_point_field_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrygroup',
            options={'permissions': (('can_supervise', 'Can modify users from specific country'),)},
        ),
        migrations.RemoveField(
            model_name='condition',
            name='latex',
        ),
    ]
