# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0041_auto_20170929_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilitySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(default='Unknown', max_length=25, verbose_name='type')),
                ('model_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('visible_online_public', models.BooleanField(verbose_name='visible online for all')),
                ('visible_online_authed', models.BooleanField(verbose_name='visible online w/authorization')),
                ('visible_in_book', models.BooleanField(verbose_name='visible in the book')),
            ],
            options={'verbose_name': 'visibility settings', 'verbose_name_plural': 'visibility settings'},
        ),
        migrations.CreateModel(
            name='VisibilitySettingsForPublicEmail',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('hosting.visibilitysettings',),
        ),
        migrations.CreateModel(
            name='VisibilitySettingsForPhone',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('hosting.visibilitysettings',),
        ),
        migrations.CreateModel(
            name='VisibilitySettingsForPlace',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('hosting.visibilitysettings',),
        ),
        migrations.CreateModel(
            name='VisibilitySettingsForFamilyMembers',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('hosting.visibilitysettings',),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_visibility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hosting.VisibilitySettings'),
        ),
        migrations.AddField(
            model_name='phone',
            name='visibility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hosting.VisibilitySettings'),
        ),
        migrations.AddField(
            model_name='place',
            name='visibility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hosting.VisibilitySettings'),
        ),
        migrations.AddField(
            model_name='place',
            name='family_members_visibility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hosting.VisibilitySettings'),
        ),
    ]
