# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_general_preferences(app_registry, schema_editor):
    Preferences = app_registry.get_model('hosting', 'Preferences')
    Profile = app_registry.get_model('hosting', 'Profile')
    for profile in Profile.all_objects.filter(user__isnull=False):
        Preferences.objects.create(profile=profile)


def shift_contact_preferences(app_registry, schema_editor, reverse=False):
    Preferences = app_registry.get_model('hosting', 'Preferences')
    for pref in Preferences.objects.all():
        if not reverse:
            pref.contact_preferences = pref.profile.contact_preferences.all()
        else:
            pref.profile.contact_preferences = pref.contact_preferences.all()


def unshift_contact_preferences(app_registry, schema_editor):
    shift_contact_preferences(app_registry, schema_editor, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0045_auto_20180107_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_analytics_consent', models.NullBooleanField(help_text='These technologies help us to improve Pasporta Servo. Through them we collect information about how visitors interact with the web site and which changes will make the interaction better.', verbose_name='I agree to be included by usage measurement tools.')),
                ('contact_preferences', models.ManyToManyField(blank=True, to='hosting.ContactPreference', verbose_name='contact preferences')),
            ],
            options={
                'verbose_name_plural': 'preferences for profile',
                'verbose_name': 'preferences for profile',
            },
        ),
        migrations.AddField(
            model_name='preferences',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pref', to='hosting.Profile', verbose_name='profile'),
        ),
        migrations.RunPython(
            create_general_preferences, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            shift_contact_preferences, reverse_code=unshift_contact_preferences
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_preferences',
        ),
    ]
