# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0046_preferences_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='public_listing',
            field=models.BooleanField(default=True, verbose_name='List my profile in search results open to the internet.'),
        ),
    ]
