# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 07:30
from __future__ import unicode_literals

from django.db import migrations
import hosting.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0054_phones_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=hosting.fields.ForeigKeyWithSuggestions(
                blank=True,
                choices='hosting.Gender',
                db_column='gender_value',
                help_text='Also known as "social sex identity". Type your own preference or select one of the suggestions.',
                to_field='name',
                verbose_name='gender'),
        ),
    ]
