# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-17 22:45
from __future__ import unicode_literals

from django.db import migrations, connection
from django.core.management.color import no_style


def add_genders(app_registry, schema_editor):
    Gender = app_registry.get_model('hosting', 'Gender')
    with connection.cursor() as cursor:
        for sql in connection.ops.sequence_reset_sql(no_style(), [Gender]):
            cursor.execute(sql)
    Gender(name_en='woman', name='virino').save()
    Gender(name_en='man', name='viro').save()


def remove_genders(app_registry, schema_editor):
    Gender = app_registry.get_model('hosting', 'Gender')
    Gender.objects.filter(name_en__in=['woman', 'man']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0056_change_place_conditions_desc'),
    ]

    operations = [
        migrations.RunPython(
            add_genders, reverse_code=remove_genders
        ),
    ]
