# Generated by Django 2.2.22 on 2021-09-19 05:45

from django.db import migrations, models
import hosting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0059_switch_phonenumber_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, help_text='Name in the official language, in latin letters; not in Esperanto (e.g.:&nbsp;Rotterdam).', max_length=255, validators=[hosting.validators.validate_not_all_caps, hosting.validators.validate_not_too_many_caps], verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='place',
            name='closest_city',
            field=models.CharField(blank=True, help_text='If your place is in a town near a bigger city. Name in the official language, in latin letters; not in Esperanto.', max_length=255, validators=[hosting.validators.validate_not_all_caps, hosting.validators.validate_not_too_many_caps], verbose_name='closest big city'),
        ),
        migrations.AlterField(
            model_name='place',
            name='contact_before',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of days before people should contact host.', null=True, verbose_name='contact this number of days in advance'),
        ),
        migrations.AlterField(
            model_name='place',
            name='max_guest',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum number of guests'),
        ),
        migrations.AlterField(
            model_name='place',
            name='max_night',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum number of nights'),
        ),
        migrations.AlterField(
            model_name='whereabouts',
            name='name',
            field=models.CharField(help_text='Name in the official language, in latin letters; not in Esperanto (e.g.:&nbsp;Rotterdam).', max_length=255, verbose_name='name'),
        ),
    ]
