# Generated by Django 2.2.22 on 2021-10-04 18:44

from django.db import migrations
import hosting.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0060_change_place_fields_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='max_guest',
            field=hosting.fields.RangeIntegerField(blank=True, help_text='Leave empty if there is no limitation.', max_value=50, min_value=1, null=True, verbose_name='maximum number of guests'),
        ),
        migrations.AlterField(
            model_name='place',
            name='max_night',
            field=hosting.fields.RangeIntegerField(blank=True, help_text='Leave empty if there is no limitation.', max_value=180, min_value=1, null=True, verbose_name='maximum number of nights'),
        ),
    ]
