# Generated by Django 2.2.27 on 2022-04-22 07:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0061_range_int_field'),
    ]

    operations = [
        # FamilyMember proxy model in admin was renamed to FamilyMemberRepr.
        migrations.CreateModel(
            name='FamilyMemberRepr',
            fields=[
            ],
            options={
                'ordering': ['first_name', 'last_name', 'id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hosting.profile',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        # FamilyMember is now a proxy model in the 'hosting' app.
        migrations.AlterModelOptions(
            name='FamilyMember',
            options={},
        ),
    ]
