# Generated by Django 2.2.27 on 2022-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0062_add_familymember_proxy_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='site_analytics_consent',
            field=models.BooleanField(
                default=None,
                help_text='These technologies help us to improve Pasporta Servo. Through them we collect information about how visitors interact with the web site and which changes will make the interaction better.',
                null=True,
                verbose_name='I agree to be included by usage measurement tools.'),
        ),
    ]
