# Generated by Django 2.2.28 on 2022-08-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0063_switch_preferences_site_analytics_consent_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='available',
            field=models.BooleanField(default=True, help_text='Is there a place to sleep on offer. If yes, you will be considered as host.', verbose_name='available'),
        ),
    ]
