# Generated by Django 3.2.15 on 2022-12-25 11:56

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0064_change_place_available_desc'),
    ]

    operations = [
        UnaccentExtension()
    ]
