# Generated by Django 3.2.20 on 2024-01-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0066_hosting_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
    ]
