# Generated by Django 3.2.20 on 2024-02-18 05:48

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hosting', '0067_remove_place_lat_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasportaServoUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
