# Generated by Django 3.2.25 on 2025-05-25 21:55

import core.fields
from django.db import migrations
import hosting.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0069_change_place_option_fields_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryregion',
            name='country',
            field=hosting.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country',
            field=hosting.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=hosting.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=hosting.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name='location',
            ),
        ),
        migrations.AlterField(
            model_name='traveladvice',
            name='content',
            field=core.fields.SimpleMDEField(verbose_name='Markdown content'),
        ),
        migrations.AlterField(
            model_name='traveladvice',
            name='countries',
            field=hosting.fields.CountryField(
                blank=True, max_length=746, multiple=True, verbose_name='countries',
            ),
        ),
        migrations.AlterField(
            model_name='whereabouts',
            name='bbox',
            field=hosting.fields.LineStringField(
                help_text='Expected diagonal: south-west lon/lat, north-east lon/lat.',
                srid=4326, verbose_name='bounding box',
            ),
        ),
        migrations.AlterField(
            model_name='whereabouts',
            name='center',
            field=hosting.fields.PointField(
                help_text='Expected: longitude/latitude position.',
                srid=4326, verbose_name='geographical center',
            ),
        ),
        migrations.AlterField(
            model_name='whereabouts',
            name='country',
            field=hosting.fields.CountryField(max_length=2, verbose_name='country'),
        ),
    ]
