# Generated by Django 4.0.10 on 2025-09-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0070_annotated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='visibility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='hosting.visibilitysettingsforphone'),
        ),
        migrations.AlterField(
            model_name='place',
            name='visibility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='hosting.visibilitysettingsforplace'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_visibility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='hosting.visibilitysettingsforpublicemail'),
        ),
    ]
