# Generated by Django 4.2.26 on 2026-01-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0071_change_model_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_details_changed_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='personal details changed on'),
        ),
    ]
