# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


def create_site_config(apps, schema_editor):
    apps.get_model('core', 'SiteConfiguration')._default_manager.create()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Pasporta Servo', max_length=30, verbose_name='site name')),
                ('google_analytics_key', models.CharField(blank=True, default='UA-99737795-1', max_length=13)),
                ('salt', models.CharField(default='salo', help_text='Salt used for encoded unique links. Change it to invalidate all links.', max_length=30, verbose_name='encryption salt')),
                ('host_min_age', models.PositiveSmallIntegerField(default=16, verbose_name='Minumum age for hosting')),
                ('meet_min_age', models.PositiveSmallIntegerField(default=13, verbose_name='Minumum age for meeting')),
                ('token_max_age', models.PositiveIntegerField(default=172800, help_text='In seconds: 2 days = 3600 x 24 x 2 = 172800')),
                ('confirmation_validity_period', models.DurationField(default=datetime.timedelta(294), help_text='Delay after which an object is no longer considered as confirmed', verbose_name='confirmation validity period')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),

        migrations.RunPython(create_site_config, reverse_code=migrations.RunPython.noop),
    ]
