# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_agreement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='withdrawn',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='withdrawn on'),
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together=set([('user', 'policy_version', 'withdrawn')]),
        ),
    ]
