# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agreement_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='opencage_api_key',
            field=models.CharField(blank=True, default='a27f7e361bdfe11881a987a6e86fb5fd', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='openmaptiles_api_key',
            field=models.CharField(blank=True, default='iQbjILhp2gs0dgNfTlIV', max_length=32),
        ),
    ]
