# Generated by Django 2.2.22 on 2021-10-02 18:10

from django.db import migrations
import hosting.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_policy_as_flatpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='host_min_age',
            field=hosting.fields.RangeIntegerField(default=17, min_value=16, verbose_name='minumum age for hosting'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meet_min_age',
            field=hosting.fields.RangeIntegerField(default=16, min_value=16, verbose_name='minumum age for meeting'),
        ),
    ]
