# Generated by Django 2.2.24 on 2021-10-30 06:44

import re
from django.db import migrations


def update_policies(app_registry, schema_editor):
    Policy = app_registry.get_model('core', 'Policy')
    for policy in Policy.objects.filter(url__startswith='/privacy-policy-'):
        policy.content = policy.content.replace("fa fa-sign-in ", "fa fa-sign-in-alt ")
        for orig_icon, repl_icon in {'chevron-down': 'angle-down', 'chevron-up': 'angle-up'}.items():
            policy.content = re.sub(
                fr'(<a href=".+?")(>\s+<span class="fa )fa-{ orig_icon } pull-right(")',
                fr'\1 class="pull-right"\2fa-{ repl_icon } fa-lg fa-fw\3',
                policy.content)
        policy.save()


def undo_policy_updates(app_registry, schema_editor):
    Policy = app_registry.get_model('core', 'Policy')
    for policy in Policy.objects.filter(url__startswith='/privacy-policy-'):
        policy.content = policy.content.replace("fa fa-sign-in-alt ", "fa fa-sign-in ")
        for orig_icon, repl_icon in {'chevron-down': 'angle-down', 'chevron-up': 'angle-up'}.items():
            policy.content = re.sub(
                fr'(<a href=".+?") class="pull-right"(>\s+<span class="fa )fa-{ repl_icon } .+?(")',
                fr'\1\2fa-{ orig_icon } pull-right\3',
                policy.content)
        policy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_range_int_field'),
    ]

    operations = [
        migrations.RunPython(update_policies, reverse_code=undo_policy_updates),
    ]
