# Generated by Django 2.2.24 on 2021-12-02 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_update_policy_fa_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent_string', models.CharField(max_length=250, verbose_name='user agent string')),
                ('user_agent_hash', models.CharField(max_length=32, verbose_name='user agent hash')),
                ('geolocation', models.CharField(blank=True, help_text='Region and country code, separated by comma.', max_length=50, verbose_name='location')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('os_name', models.CharField(blank=True, max_length=15, verbose_name='operating system')),
                ('os_version', models.CharField(blank=True, max_length=15, verbose_name='operating system version')),
                ('browser_name', models.CharField(blank=True, max_length=15, verbose_name='browser')),
                ('browser_version', models.CharField(blank=True, max_length=15, verbose_name='browser version')),
                ('device_type', models.CharField(blank=True, max_length=30, verbose_name='type of device')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user browser',
                'verbose_name_plural': 'user browsers',
            },
        ),
    ]
