# Generated by Django 2.2.27 on 2022-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userbrowser_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrowser',
            name='browser_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='browser'),
        ),
        migrations.AlterField(
            model_name='userbrowser',
            name='os_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='operating system'),
        ),
    ]
