# Generated by Django 3.2.20 on 2023-12-10 22:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_userbrowser_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='mapping_services_api_keys',
            field=models.JSONField(default=core.models.default_api_keys, verbose_name='API keys for mapping services'),
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='opencage_api_key',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='openmaptiles_api_key',
        ),
    ]
