# Generated by Django 3.2.25 on 2025-04-16 18:08

from typing import TYPE_CHECKING, cast

from django.apps.registry import Apps
from django.db import migrations, models

from core.utils import version_to_numeric_repr

if TYPE_CHECKING:
    from core.models import UserBrowser as UserBrowserModel


def calculate_numeric_representation(apps: Apps, schema_editor):
    UserBrowser = cast('type[UserBrowserModel]', apps.get_model('core', 'UserBrowser'))

    def set_numeric_field(user_browser: 'UserBrowserModel', field_name: str):
        field = cast(
            models.DecimalField,
            user_browser._meta.get_field(f'{field_name}_numeric'))
        precision = field.decimal_places
        setattr(
            user_browser,
            f'{field_name}_numeric',
            version_to_numeric_repr(getattr(user_browser, field_name), precision)
        )

    for user_browser in UserBrowser.objects.all():
        set_numeric_field(user_browser, 'browser_version')
        set_numeric_field(user_browser, 'os_version')
        user_browser.save(update_fields=['browser_version_numeric', 'os_version_numeric'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_policy_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrowser',
            name='browser_version_numeric',
            field=models.DecimalField(decimal_places=35, max_digits=60, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbrowser',
            name='os_version_numeric',
            field=models.DecimalField(decimal_places=35, max_digits=60, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            calculate_numeric_representation, migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='userbrowser',
            name='browser_version_numeric',
            field=models.DecimalField(decimal_places=35, max_digits=60),
        ),
        migrations.AlterField(
            model_name='userbrowser',
            name='os_version_numeric',
            field=models.DecimalField(decimal_places=35, max_digits=60),
        ),
    ]
