# Generated by Django 4.2.27 on 2026-03-29 17:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_userbrowser_numeric_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFlag',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                )),
                ('name', models.CharField(
                    max_length=100, unique=True, verbose_name='Name',
                    help_text='The human/computer readable name.',
                )),
                ('everyone', models.BooleanField(
                    blank=True, null=True, verbose_name='Everyone',
                    help_text=(
                        'Flip this flag on (Yes) or off (No) for everyone, overriding all'
                        ' other settings. Leave as Unknown to use normally.'
                    ),
                )),
                ('percent', models.DecimalField(
                    blank=True, decimal_places=1, max_digits=3, null=True,
                    verbose_name='Percent',
                    help_text=(
                        'A number between 0.0 and 99.9 to indicate a percentage of users'
                        ' for whom this flag will be active.'
                    ),
                )),
                ('testing', models.BooleanField(
                    default=False, verbose_name='Testing',
                    help_text='Allow this flag to be set for a session for user testing',
                )),
                ('superusers', models.BooleanField(
                    default=True, verbose_name='Superusers',
                    help_text='Flag always active for superusers?',
                )),
                ('staff', models.BooleanField(
                    default=False, verbose_name='Staff',
                    help_text='Flag always active for staff?',
                )),
                ('authenticated', models.BooleanField(
                    default=False, verbose_name='Authenticated',
                    help_text='Flag always active for authenticated users?',
                )),
                ('languages', models.TextField(
                    blank=True, default='', verbose_name='Languages',
                    help_text=(
                        'Activate this flag for users with one of these languages'
                        ' (comma-separated list)'
                    ),
                )),
                ('rollout', models.BooleanField(
                    default=False, verbose_name='Rollout',
                    help_text='Activate roll-out mode?',
                )),
                ('note', models.TextField(
                    blank=True, verbose_name='Note',
                    help_text='Note where this Flag is used.',
                )),
                ('created', models.DateTimeField(
                    db_index=True, default=django.utils.timezone.now, verbose_name='Created',
                    help_text='Date when this Flag was created.',
                )),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Modified',
                    help_text='Date when this Flag was last modified.',
                )),
                ('groups', models.ManyToManyField(
                    blank=True, to='auth.group', verbose_name='Groups',
                    help_text='Activate this flag for these user groups.',
                )),
                ('users', models.ManyToManyField(
                    blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users',
                    help_text='Activate this flag for these users.',
                )),
            ],
            options={
                'verbose_name': 'site flag',
                'verbose_name_plural': 'site flags',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSwitch',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                )),
                ('name', models.CharField(
                    max_length=100, unique=True, verbose_name='Name',
                    help_text='The human/computer readable name.',
                )),
                ('active', models.BooleanField(
                    default=False, verbose_name='Active',
                    help_text='Is this switch active?',
                )),
                ('note', models.TextField(
                    blank=True, verbose_name='Note',
                    help_text='Note where this Switch is used.',
                )),
                ('created', models.DateTimeField(
                    db_index=True, default=django.utils.timezone.now, verbose_name='Created',
                    help_text='Date when this Switch was created.',
                )),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Modified',
                    help_text='Date when this Switch was last modified.',
                )),
            ],
            options={
                'verbose_name': 'site switch',
                'verbose_name_plural': 'site switches',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSample',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                )),
                ('name', models.CharField(
                    max_length=100, unique=True, verbose_name='Name',
                    help_text='The human/computer readable name.',
                )),
                ('percent', models.DecimalField(
                    decimal_places=1, max_digits=4, verbose_name='Percent',
                    help_text=(
                        'A number between 0.0 and 100.0 to indicate a percentage of the time'
                        ' this sample will be active.'
                    ),
                )),
                ('note', models.TextField(
                    blank=True, verbose_name='Note',
                    help_text='Note where this Sample is used.',
                )),
                ('created', models.DateTimeField(
                    db_index=True, default=django.utils.timezone.now, verbose_name='Created',
                    help_text='Date when this Sample was created.',
                )),
                ('modified', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Modified',
                    help_text='Date when this Sample was last modified.',
                )),
            ],
            options={
                'verbose_name': 'site sample',
                'verbose_name_plural': 'site samples',
                'abstract': False,
            },
        ),
    ]
