# Generated by Django 4.2.26 on 2026-01-11 03:03

from datetime import timedelta
from functools import partial

from django.apps.registry import Apps
from django.db import migrations
from django.utils import timezone


def create_scheduled_tasks(apps: Apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')

    # Ensure that weekly tasks to notify administrators about pending chat messages
    # are scheduled. Target weekday can be Monday = 0 ... Friday = 4.
    def calculate_first_scheduled_run(target_weekday: int):
        now = timezone.now().astimezone(timezone.utc)
        target = (
            (now + timedelta(days=(target_weekday - now.weekday()) % 7))
            .replace(hour=14, minute=0, second=0, microsecond=0)
        )
        if target <= now:
            target += timedelta(days=7)
        return target

    Schedule.objects.update_or_create(
        name='Pending chat messages reminder (Tuesday)',
        defaults={
            'func': 'chat.apps.notify_pending_messages',
            'schedule_type': 'W',  # WEEKLY
            'repeats': -1,
            'next_run': partial(calculate_first_scheduled_run, target_weekday=1),
        }
    )
    Schedule.objects.update_or_create(
        name='Pending chat messages reminder (Friday)',
        defaults={
            'func': 'chat.apps.notify_pending_messages',
            'schedule_type': 'W',  # WEEKLY
            'repeats': -1,
            'next_run': partial(calculate_first_scheduled_run, target_weekday=4),
        }
    )


def remove_scheduled_tasks(apps: Apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')

    Schedule.objects.filter(name__startswith='Pending chat messages reminder').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('django_q', '0018_task_success_index'),
    ]

    operations = [
        migrations.RunPython(create_scheduled_tasks, remove_scheduled_tasks),
    ]
