


LANGUAGES = {
    "AD": ["ca"],
    "AE": ["ar"],
    "AF": ["fa", "ps"],
    "AG": ["en"],
    "AI": ["en"],
    "AL": ["sq"],
    "AM": ["hy"],
    "AN": ["nl", "en"],
    "AO": ["pt"],
    "AQ": [""],
    "AR": ["es"],
    "AS": ["en", "sm"],
    "AT": ["de"],
    "AU": ["en"],
    "AW": ["nl", "pap"],
    "AX": ["sv"],
    "AZ": ["az"],
    "BA": ["bs", "hr", "sr"],
    "BB": ["en"],
    "BD": ["bn"],
    "BE": ["nl", "fr", "de"],
    "BF": ["fr"],
    "BG": ["bg"],
    "BH": ["ar"],
    "BI": ["fr"],
    "BJ": ["fr"],
    "BL": ["fr"],
    "BM": ["en"],
    "BN": ["ms"],
    "BO": ["es", "qu", "ay"],
    "BR": ["pt"],
    "BS": ["en"],
    "BT": ["dz"],
    "BV": ["no"],
    "BW": ["en", "tn"],
    "BY": ["be", "ru"],
    "BZ": ["en"],
    "CA": ["en", "fr"],
    "CC": ["en"],
    "CD": ["fr"],
    "CF": ["fr"],
    "CG": ["fr"],
    "CH": ["de", "fr", "it", "rm"],
    "CI": ["fr"],
    "CK": ["en", "rar"],
    "CL": ["es"],
    "CM": ["fr", "en"],
    "CN": ["zh"],
    "CO": ["es"],
    "CR": ["es"],
    "CU": ["es"],
    "CV": ["pt"],
    "CX": ["en"],
    "CY": ["el", "tr"],
    "CZ": ["cs"],
    "DE": ["de"],
    "DJ": ["fr", "ar", "so"],
    "DK": ["da"],
    "DM": ["en"],
    "DO": ["es"],
    "DZ": ["ar"],
    "EC": ["es"],
    "EE": ["et"],
    "EG": ["ar"],
    "EH": ["ar", "es", "fr"],
    "ER": ["ti", "ar", "en"],
    "ES": ["ast", "ca", "es", "eu", "gl"],
    "ET": ["am", "om"],
    "FI": ["fi", "sv", "se"],
    "FJ": ["en"],
    "FK": ["en"],
    "FM": ["en"],
    "FO": ["fo"],
    "FR": ["fr"],
    "GA": ["fr"],
    "GB": ["en", "ga", "cy", "gd", "kw"],
    "GD": ["en"],
    "GE": ["ka"],
    "GF": ["fr"],
    "GG": ["en"],
    "GH": ["en"],
    "GI": ["en"],
    "GL": ["kl", "da"],
    "GM": ["en"],
    "GN": ["fr"],
    "GP": ["fr"],
    "GQ": ["es", "fr", "pt"],
    "GR": ["el"],
    "GS": ["en"],
    "GT": ["es"],
    "GU": ["en", "ch"],
    "GW": ["pt"],
    "GY": ["en"],
    "HK": ["zh", "en"],
    "HM": ["en"],
    "HN": ["es"],
    "HR": ["hr"],
    "HT": ["fr", "ht"],
    "HU": ["hu"],
    "ID": ["id"],
    "IE": ["en", "ga"],
    "IL": ["he"],
    "IM": ["en"],
    "IN": ["hi", "en"],
    "IO": ["en"],
    "IQ": ["ar", "ku"],
    "IR": ["fa"],
    "IS": ["is"],
    "IT": ["it", "de", "fr"],
    "JE": ["en"],
    "JM": ["en"],
    "JO": ["ar"],
    "JP": ["ja"],
    "KE": ["sw", "en"],
    "KG": ["ky", "ru"],
    "KH": ["km"],
    "KI": ["en"],
    "KM": ["ar", "fr"],
    "KN": ["en"],
    "KP": ["ko"],
    "KR": ["ko", "en"],
    "KW": ["ar"],
    "KY": ["en"],
    "KZ": ["kk", "ru"],
    "LA": ["lo"],
    "LB": ["ar", "fr"],
    "LC": ["en"],
    "LI": ["de"],
    "LK": ["si", "ta"],
    "LR": ["en"],
    "LS": ["en", "st"],
    "LT": ["lt"],
    "LU": ["lb", "fr", "de"],
    "LV": ["lv"],
    "LY": ["ar"],
    "MA": ["ar"],
    "MC": ["fr"],
    "MD": ["ru", "uk", "ro"],
    "ME": ["srp", "sq", "bs", "hr", "sr"],
    "MF": ["fr"],
    "MG": ["mg", "fr"],
    "MH": ["en", "mh"],
    "MK": ["mk"],
    "ML": ["fr"],
    "MM": ["my"],
    "MN": ["mn"],
    "MO": ["zh", "pt"],
    "MP": ["ch"],
    "MQ": ["fr"],
    "MR": ["ar", "fr"],
    "MS": ["en"],
    "MT": ["mt", "en"],
    "MU": ["mfe", "fr", "en"],
    "MV": ["dv"],
    "MW": ["en", "ny"],
    "MX": ["es"],
    "MY": ["ms"],
    "MZ": ["pt"],
    "NA": ["en", "sf", "de"],
    "NC": ["fr"],
    "NE": ["fr"],
    "NF": ["en", "pih"],
    "NG": ["en"],
    "NI": ["es"],
    "NL": ["nl"],
    "NO": ["nb", "nn", "no", "se"],
    "NP": ["ne"],
    "NR": ["na", "en"],
    "NU": ["niu", "en"],
    "NZ": ["mi", "en"],
    "OM": ["ar"],
    "PA": ["es"],
    "PE": ["es"],
    "PF": ["fr"],
    "PG": ["en", "tpi", "ho"],
    "PH": ["en", "tl"],
    "PK": ["en", "ur"],
    "PL": ["pl"],
    "PM": ["fr"],
    "PN": ["en", "pih"],
    "PR": ["es", "en"],
    "PS": ["ar", "he"],
    "PT": ["pt"],
    "PW": ["en", "pau", "ja", "sov", "tox"],
    "PY": ["es", "gn"],
    "QA": ["ar"],
    "RE": ["fr"],
    "RO": ["ro"],
    "RS": ["sr"],
    "RU": ["ru"],
    "RW": ["rw", "fr", "en"],
    "SA": ["ar"],
    "SB": ["en"],
    "SC": ["fr", "en", "crs"],
    "SD": ["ar", "en"],
    "SE": ["sv"],
    "SG": ["en", "ms", "zh", "ta"],
    "SH": ["en"],
    "SI": ["sl"],
    "SJ": ["no"],
    "SK": ["sk"],
    "SL": ["en"],
    "SM": ["it"],
    "SN": ["fr"],
    "SO": ["so", "ar"],
    "SR": ["nl"],
    "ST": ["pt"],
    "SS": ["en"],
    "SV": ["es"],
    "SY": ["ar"],
    "SZ": ["en", "ss"],
    "TC": ["en"],
    "TD": ["fr", "ar"],
    "TF": ["fr"],
    "TG": ["fr"],
    "TH": ["th"],
    "TJ": ["tg", "ru"],
    "TK": ["tkl", "en", "sm"],
    "TL": ["pt", "tet"],
    "TM": ["tk"],
    "TN": ["ar"],
    "TO": ["en"],
    "TR": ["tr"],
    "TT": ["en"],
    "TV": ["en"],
    "TW": ["zh"],
    "TZ": ["sw", "en"],
    "UA": ["uk"],
    "UG": ["en", "sw"],
    "UM": ["en"],
    "US": ["en"],
    "UY": ["es"],
    "UZ": ["uz", "kaa"],
    "VA": ["it"],
    "VC": ["en"],
    "VE": ["es"],
    "VG": ["en"],
    "VI": ["en"],
    "VN": ["vi"],
    "VU": ["bi", "en", "fr"],
    "WF": ["fr"],
    "WS": ["sm", "en"],
    "YE": ["ar"],
    "YT": ["fr"],
    "ZA": ["zu", "xh", "af", "st", "tn", "en"],
    "ZM": ["en"],
    "ZW": ["en", "sn", "nd"]; 
}


LOCAL_NAME = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Shqipëria",
    "AM": "Armenia",
    "AN": "De Nederlandse Antillen",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Österreich",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Aland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosna i Hercegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "België - Belgique - Belgien",
    "BF": "Burkina Faso",
    "BG": "България",
    "BH": "البحرين",
    "BI": "Burundi",
    "BJ": "Bénin",
    "BL": "Saint Barthélemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia",
    "BR": "Brasil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Беларусь",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "République Démocratique du Congo",
    "CF": "Centrafrique",
    "CG": "République du Congo",
    "CH": "Switzerland",
    "CI": "Côte d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon;Cameroun",
    "CN": "China 中国",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CX": "Christmas Island",
    "CY": "Κύπρος",
    "CZ": "Česká republika",
    "DE": "Deutschland",
    "DJ": "جيبوتي;Djibouti",
    "DK": "Danmark",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "DZ": "الجزائر",
    "EC": "Ecuador",
    "EE": "Eesti",
    "EG": "Egypt / مصر",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "España",
    "ET": "Ethiopia",
    "FI": "Suomi",
    "FJ": "Fiji",
    "FK": "Falkland Islands",
    "FM": "Micronesia",
    "FO": "Føroyar/Færøerne",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia / საქართველო",
    "GF": "Guyane Française",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Kalaallit Nunaat",
    "GM": "The Gambia",
    "GN": "Guinée",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Ελλάδα",
    "GS": "South Georgia and South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guiné-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Hrvatska",
    "HT": "Haiti",
    "HU": "Magyarország",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "ישראל",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "ایران",
    "IS": "Ísland",
    "IT": "Italia",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan / الأُرْدُن",
    "JP": "日本 (Japan)",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comores;ﺍﻟﻘﻤﺮي;Komori",
    "KN": "Saint Kitts and Nevis",
    "KP": "북조선",
    "KR": "대한민국",
    "KW": "Kuwait / الكويت",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Laos",
    "LB": "لبنان Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lietuva",
    "LU": "Luxembourg",
    "LV": "Latvija",
    "LY": "Libya / ليبيا",
    "MA": "Maroc",
    "MC": "Monaco",
    "MD": "Moldova",
    "ME": "Crna Gora",
    "MF": "Saint Martin",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Македонија",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Монгол Улс",
    "MO": "Macao",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "موريتانيا",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "México",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "Nouvelle-Calédonie",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Nederland",
    "NO": "Norge – Noreg",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "سلطنة عُمان Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "Polynésie française",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "پاکستان",
    "PL": "Polska",
    "PM": "Saint-Pierre-et-Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestinian Territory",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "قطر Qatar",
    "RE": "Réunion",
    "RO": "România",
    "RS": "Србија (Serbia)",
    "RU": "Россия",
    "RW": "Rwanda",
    "SA": "Saudi Arabia / السعودية",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "السودان ‎al-Sūdān",
    "SE": "Sverige",
    "SG": "Singapore",
    "SH": "Saint Helena",
    "SI": "Slovenija",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovensko",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Sénégal",
    "SO": "Somalia / الصومال",
    "SR": "Suriname",
    "ST": "São Tomé e Príncipe",
    "SS": "South Sudan",
    "SV": "El Salvador",
    "SY": "Sūriyya سوريا",
    "SZ": "Swaziland",
    "TC": "Turks and Caicos Islands",
    "TD": "Tchad / تشاد",
    "TF": "Terres australes et antarctiques françaises",
    "TG": "Togo",
    "TH": "ประเทศไทย",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste; Timor Lorosa'e",
    "TM": "Türkmenistan",
    "TN": "تونس",
    "TO": "Tonga",
    "TR": "Türkiye",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Україна",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Città del Vaticano",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "United States Virgin Islands",
    "VN": "Việt Nam",
    "VU": "Vanuatu",
    "WF": "Wallis-et-Futuna",
    "WS": "Samoa",
    "YE": "اليَمَن al-Yaman",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}
