# Generated by Django 3.2.25 on 2025-05-25 21:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171030_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=core.fields.SimpleMDEField(verbose_name='Markdown content'),
        ),
    ]
