# Generated by Django 3.2.20 on 2023-10-26 06:00

from django.db import migrations


def create_product(apps, schema_editor):
    apps.get_model('shop', 'Product').objects.update_or_create(
        name="Financial support / Financa subteno",
        code='Donation',
        price=3.00,
        low_price=3.00,
    )


def remove_product(apps, schema_editor):
    apps.get_model('shop', 'Product').objects.filter(code='Donation').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_product, remove_product),
    ]
