# -*- coding: utf-8 -*-

COUNTRIES = {
    "Afganio": "AF",
    "Albanio": "AL",
    "Alĝerio": "DZ",
    "Argentino": "AR",
    "Aŭstralio": "AU",
    "Aŭstrio": "AT",
    "Azerbajĝano": "AZ",
    "Bahamoj": "BS",
    "Belgio": "BE",
    "Benino": "BJ",
    "Bjelorusio": "BY",
    "Bosnio-Hercegovino": "BA",
    "Brazilo": "BR",
    "Britio": "GB",
    "Bulgario": "BG",
    "Burundio": "BI",
    "Ĉeĥio": "CZ",
    "Ĉilio": "CL",
    "Ĉinio": "CN",
    "Cipro": "CY",
    "Danio": "DK",
    "Dominika Resp.": "DO",
    "Egiptio": "EG",
    "Estonio": "EE",
    "Finnlando": "FI",
    "Francio": "FR",
    "Ganao": "GH",
    "Germanio": "DE",
    "Grekio": "GR",
    "Gvatemalo": "GT",
    "Hinda Unio": "IN",
    "Hispanio": "ES",
    "Honkongo (Ĉin.)": "HK",
    "Hungario": "HU",
    "Indonezio": "ID",
    "Internacie": "SM",
    "Irano": "IR",
    "Irlando": "IE",
    "Islando": "IS",
    "Israelo": "IL",
    "Italio": "IT",
    "Japanio": "JP",
    "Kamboĝo": "KH",
    "Kanado": "CA",
    "Kartvelio": "GE",
    "Kazaĥio": "KZ",
    "Kenjo": "KE",
    "Kirgizio": "KI",
    "Kolombio": "CO",
    "Komoroj": "KM",
    "Kongo, DR": "CD",
    "Korea Resp.": "KR",
    "Kostariko": "CR",
    "Kroatio": "HR",
    "Kubo": "CU",
    "Latvio": "LV",
    "Litovio": "LT",
    "Luksemburgio": "LU",
    "Madagaskaro": "MG",
    "Makedonio": "MK",
    "Malajzio": "MY",
    "Malio": "ML",
    "Malto": "MT",
    "Maroko": "MA",
    "Meksiko": "MX",
    "Moldavio": "MD",
    "Mongolio": "MN",
    "Nederlando": "NL",
    "Nepalo": "NP",
    "Niĝerio": "NE",
    "Niĝerlando": "NG",
    "Norvegio": "NO",
    "Nov-Kaledonio (Fr.)": "NC",
    "Nov-Zelando": "NZ",
    "Pakistano": "PK",
    "Panamo": "PA",
    "Peruo": "PE",
    "Pollando": "PL",
    "Portugalio": "PT",
    "Reunio (Fr.)": "RE",
    "Rumanio": "RO",
    "Rusio": "RU",
    "Salvadoro": "SV",
    "Senegalio": "SN",
    "Serbio": "RS",
    "Slovakio": "SK",
    "Slovenio": "SI",
    "Somalio": "SO",
    "Sud-Afriko": "ZA",
    "Svazilando": "SZ",
    "Svedio": "SE",
    "Svislando": "CH",
    "Taĝikio": "TJ",
    "Tajlando": "TH",
    "Tajvano": "TW",
    "Tanzanio": "TZ",
    "Togolando": "TG",
    "Turkio": "TR",
    "Ukrainio": "UA",
    "Un. Arabaj Emirejoj": "AE",
    "Urugvajo": "UY",
    "Usono": "US",
    "Uzbekio": "UZ",
    "Venezuelo": "VE",
    "Vjetnamio": "VN",
    "Zimbabvo": "ZW",
}
